services:
  - type: web
    name: terminfinder-api
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: terminfinder-db
          property: connectionString
      - key: DB_SCHEMA
        value: terminfinder
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false

databases:
  - name: terminfinder-db
    databaseName: terminfinder_db
    user: terminfinder_user
    plan: free